tech_corp_front_timeline:
  path: /timeline
  defaults: { _controller: TechCorpFrontBundle:Timeline:timeline }

tech_corp_front_about:
  path:     /about
  defaults: { _controller: TechCorpFrontBundle:Static:about }