tech_corp_front_homepage:
    path:     /
    defaults: { _controller: TechCorpFrontBundle:Static:homepage }

tech_corp_front_user_timeline:
    path: /timeline/{userId}
    defaults: { _controller: TechCorpFrontBundle:Timeline:userTimeline }
  
tech_corp_front_friends_timeline:
    path: /newsfeed
    defaults: { _controller: TechCorpFrontBundle:Timeline:friendsTimeline }

tech_corp_front_user_add_friend:
  path: /user/add-friend/{friendId}
  defaults: { _controller: techcorp.usercontroller:addFriendAction }
  requirements: { method: POST }

tech_corp_front_user_remove_friend:
  path: /user/remove-friend/{friendId}
  defaults: { _controller: techcorp.usercontroller:removeFriendAction }
  requirements: { method: POST }

tech_corp_front_comment_add:
  path: /comment/add/{statusId}
  defaults: { _controller: TechCorpFrontBundle:Comment:addComment }
  requirements: { method: POST }