imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ TechCorpFrontBundle, FOSUserBundle ]
    node: /usr/bin/nodejs
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        uglifycss:
          bin: /usr/local/bin/uglifycss
    assets:
      bootstrap_js:
        inputs:
        - '@TechCorpFrontBundle/Resources/public/js/external/jquery-2.2.1.min.js'
        - '@TechCorpFrontBundle/Resources/public/js/external/bootstrap.min.js'
      bootstrap_css:
        inputs:
        - '@TechCorpFrontBundle/Resources/public/css/external/bootstrap.min.css'
        - '@TechCorpFrontBundle/Resources/public/css/external/bootstrap-theme.min.css'

      font-awesome-otf:
          inputs: '%kernel.root_dir%/../src/TechCorp/FrontBundle/Resources/public/fonts/FontAwesome.otf'
          output: 'fonts/FontAwesome.otf'
      font-awesome-eot:
          inputs: '%kernel.root_dir%/../src/TechCorp/FrontBundle/Resources/public/fonts/fontawesome-webfont.eot'
          output: 'fonts/fontawesome-webfont.eot'
      font-awesome-svg:
          inputs: '%kernel.root_dir%/../src/TechCorp/FrontBundle/Resources/public/fonts/fontawesome-webfont.svg'
          output: 'fonts/fontawesome-webfont.svg'
      font-awesome-ttf:
          inputs: '%kernel.root_dir%/../src/TechCorp/FrontBundle/Resources/public/fonts/fontawesome-webfont.ttf'
          output: 'fonts/fontawesome-webfont.ttf'
      font-awesome-woff:
          inputs: '%kernel.root_dir%/../src/TechCorp/FrontBundle/Resources/public/fonts/fontawesome-webfont.woff'
          output: 'fonts/fontawesome-webfont.woff'

        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: TechCorp\FrontBundle\Entity\User
    
services:
    fos_user.doctrine_registry:
        alias: doctrine

fos_js_routing:
  routes_to_expose: [ tech_corp_front_user_add_friend, tech_corp_front_user_remove_friend ]

jms_i18n_routing:
  default_locale: fr
  locales: [en, fr]
  strategy: prefix_except_default